# Generated by Django 3.2.5 on 2021-07-05 18:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_auto_20210705_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='brandprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='brandprofile',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='brandprofile',
            name='zip',
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='address',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.billingaddress'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 18, 17, 24, 108309, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 18, 17, 24, 116055, tzinfo=utc)),
        ),
    ]
