# Generated by Django 3.2.5 on 2021-07-07 03:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_auto_20210705_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 3, 33, 6, 380794, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 3, 33, 6, 413207, tzinfo=utc)),
        ),
    ]
