# Generated by Django 3.2.5 on 2023-01-30 15:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_auto_20210707_0333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=250, null=True)),
                ('instagram_username', models.CharField(blank=True, max_length=250, null=True)),
                ('website_link', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.SlugField(blank=True, default='', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_type',
            field=models.CharField(choices=[('', ''), ('Apparel', 'Apparel'), ('Gothic', 'Gothic'), ('Streetwears', 'Streetwears'), ('Alternative Fashion', 'Alternative Fashion'), ('Artifacts', 'Artifacts')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='brand',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 30, 15, 48, 5, 408837, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.billingaddress'),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='collection',
            field=models.CharField(choices=[('Choose your desired collection', 'Choose your desired collection'), ('Tees', 'Tees'), ('Rings', 'Rings'), ('Joggers and Track', 'Joggers and Track'), ('Chains & Necklaces', 'Chains & Necklaces'), ('Jeans', 'Jeans'), ('Jackets', 'Jackets'), ('Skating', 'Skating'), ('Caps and Hats', 'Caps and Hats'), ('Skating', 'Skating'), ('Sweatshirts and Hoodies', 'Sweatshirts and Hoodies'), ('Kicks and Slides', 'Kicks and Slides'), ('Masks', 'Masks'), ('Shades', 'Shades'), ('Lumberjacks and Vintage', 'Lumberjacks and Vintage'), ('Piercings and Studs', 'Piercings and Studs'), ('Baggy Wears', 'Baggy Wears'), ('Tattoos', 'Tattoos'), ('Graffiti', 'Graffiti')], default='Choose your desired collection', max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 30, 15, 48, 5, 418615, tzinfo=utc)),
        ),
    ]
