# Generated by Django 3.2.5 on 2023-03-03 11:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0007_auto_20230303_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 11, 44, 48, 669269, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.billingaddress'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 11, 44, 48, 681609, tzinfo=utc)),
        ),
    ]
