# Generated by Django 3.2.5 on 2023-03-10 10:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0009_auto_20230303_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandise',
            name='collection',
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_type',
            field=models.CharField(choices=[('Clothing and Apparel', 'Clothing and Apparel'), ('Accessories', 'Accessories'), ('Arts', 'Arts'), ('Footwears & Canvas', 'Footwears & Canvas')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='brand',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 10, 39, 47, 961449, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 10, 39, 47, 972300, tzinfo=utc)),
        ),
    ]
