# Generated by Django 3.2.5 on 2023-03-16 09:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0010_auto_20230310_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchandiseGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(default='', upload_to='Merch Image')),
                ('image_2', models.ImageField(default='', upload_to='Merch Image')),
                ('image_3', models.ImageField(default='', upload_to='Merch Image')),
                ('image_4', models.ImageField(default='', upload_to='Merch Image')),
                ('image_5', models.ImageField(default='', upload_to='Merch Image')),
                ('image_6', models.ImageField(default='', upload_to='Merch Image')),
            ],
        ),
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
        migrations.AddField(
            model_name='brand',
            name='username',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='display_picture',
            field=models.ImageField(default='', upload_to='Brands/Display Picture'),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 16, 9, 39, 57, 412885, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 16, 9, 39, 57, 422505, tzinfo=utc)),
        ),
    ]
