# Generated by Django 3.2.5 on 2023-03-16 10:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0013_auto_20230316_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='brand',
        ),
        migrations.AlterField(
            model_name='brand',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 16, 10, 41, 8, 328534, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 16, 10, 41, 8, 336270, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='MerchandisesList',
        ),
    ]
