# Generated by Django 3.2.5 on 2023-03-19 17:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0014_auto_20230316_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandisegallery',
            name='brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='brands.brand'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 17, 42, 34, 533222, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 17, 42, 34, 542790, tzinfo=utc)),
        ),
    ]
