# Generated by Django 3.2.5 on 2023-03-19 23:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0016_auto_20230319_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 23, 43, 28, 556066, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.brand'),
        ),
        migrations.AlterField(
            model_name='merchandisegallery',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchandise_gallery', to='brands.brand'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 23, 43, 28, 566879, tzinfo=utc)),
        ),
    ]
