# Generated by Django 3.2.5 on 2023-03-20 00:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0017_auto_20230319_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 0, 7, 20, 305032, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='brand',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.brand'),
        ),
        migrations.AlterField(
            model_name='merchandisegallery',
            name='brand',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchandise_gallery', to='brands.brand'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 0, 7, 20, 315178, tzinfo=utc)),
        ),
    ]
