# Generated by Django 3.2.5 on 2023-03-20 00:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0018_auto_20230320_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandise',
            name='images',
        ),
        migrations.RemoveField(
            model_name='merchandisegallery',
            name='brand',
        ),
        migrations.AddField(
            model_name='merchandisegallery',
            name='merchandise',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchandise_gallery', to='brands.merchandise'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 0, 13, 55, 40464, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 0, 13, 55, 53306, tzinfo=utc)),
        ),
    ]
